matrix:
  include:
    - os: linux
    - os: osx
  allow_failures:
    - os: linux

branches:
  only:
    - 2.0

language: cpp

before_install:
  - |
    case "${TRAVIS_OS_NAME}" in
      "linux")
        CMAKE_URL="http://www.cmake.org/files/v3.5/cmake-3.5.2-Linux-x86_64.tar.gz"
        mkdir my_cmake && travis_retry wget --no-check-certificate --quiet -O - ${CMAKE_URL} | tar --strip-components=1 -xz -C my_cmake
        export PATH=${TRAVIS_BUILD_DIR}/my_cmake/bin:${PATH}
        ;;
    esac
  - cmake --version

install:
  - git submodule update --init --recursive
  - mkdir TRAVIS_BUILD
  - cd TRAVIS_BUILD

script:
  - |
    case "${TRAVIS_OS_NAME}" in
      "linux")
        ../prepmake.sh ../examples/FBTestPlugin ./
        make -j4
        ;;
      "osx")
        ../prepmac.sh  ../examples/FBTestPlugin ./
        xcodebuild -parallelizeTargets -jobs 4 | egrep '^(/.+:[0-9+:[0-9]+:.(error):|fatal|===)' -
        ;;
    esac
