#!/bin/bash

# Find all .cpp, .h, and .mm files
FILES=$(find . -type f \( -name '*.cpp' -o -name '*.h' -o -name '*.mm' \))

# Process each file
for FILE in $FILES; do
    echo "Expanding $FILE..."
    expand -t 4 "$FILE" > "${FILE}_"
    mv -v "${FILE}_" "$FILE"
done
